version: '3.8'

services:
  web:
    build: .
    image: intership-be
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.env
    volumes:
      - E:/BE-Intership/intership-backend/app:/intership-backend/app
  postgres:
      image: postgres
      restart: always
      ports:
        - 5432:5432
      env_file:
      - ./.env
  redis:
      image: redis/redis-stack
      restart: always
      ports:
        - 6379:6379
      env_file:
      - ./.env