version: '3.8'

services:
#  web:
#    build: .
#    image: intership-be
#    restart: always
#    ports:
#      - 8000:8000
#    depends_on:
#      - postgres
#      - redis
#    env_file:
#      - ./.env
#    volumes:
#      - ./app:/intership-backend/app
  postgres:
      image: postgres
      restart: no
      ports:
        - 5432:5432
      env_file:
      - ./.env
      container_name: postgres
  redis:
      image: redis/redis-stack
      restart: no
      ports:
        - 6379:6379
      env_file:
      - ./.env
      container_name: redis