"""add_time_to_pass

Revision ID: 07df854b552f
Revises: f313a9d014c9
Create Date: 2023-08-18 14:23:26.584532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07df854b552f'
down_revision = 'f313a9d014c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('time_to_pass', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'time_to_pass')
    # ### end Alembic commands ###
